### ISSUE TITLE
Can't find log path

### ISSUE THREAD

**Issue by alessandrobelli** [gregstewart/farseer#8]
Hello!
My hearhstone path is not the usual path, so the npm file can't start.
Where I can change my path?

**Comment by losttime** [comment]
Provide a config object when you instantiate Farseer:

```
var Farseer = require('farseer').default;
var farseer = new Farseer({
  logFile: path.join('C:', 'custom', 'path', 'wherever', 'output_log.txt')
});
```

**Comment by gregstewart** [comment]
Thanks again @losttime for helping out! @alessandrobelli apologies for not responding sooner, I hope @losttime answer helped you.
